import { getFlightOperationsData } from "../api";
import {
    DataTable,
    DetailList,
    MetricGrid,
    ModulePage,
    StatusTag,
} from "../components/ModuleData";
import {
    formatMinutes,
    formatNumber,
    formatPercent,
} from "../components/moduleFormatters";
import { useModuleData } from "../hooks/useModuleData";

function routeLabel(row) {
    return `${row.origin} -> ${row.destination}`;
}

export function FlightOperations() {
    const { data, loading, error, refreshedAt, refresh } = useModuleData(getFlightOperationsData);
    const kpis = data?.kpis || {};

    return (
        <ModulePage
            summary="Flight operations is now wired to the Django flight-operations endpoint instead of the local demo feed."
            generatedAt={data?.generated_at}
            refreshedAt={refreshedAt}
            loading={loading}
            error={error}
            onRefresh={refresh}
        >
            <MetricGrid
                items={[
                    { label: "Total Flights", value: formatNumber(kpis.total_flights, 0) },
                    { label: "Arrivals", value: formatNumber(kpis.arrivals, 0) },
                    { label: "Departures", value: formatNumber(kpis.departures, 0) },
                    { label: "On-Time Departure", value: formatPercent(kpis.on_time_departure_pct), tone: "low" },
                    { label: "Avg Arrival Delay", value: formatMinutes(kpis.avg_arrival_delay_min), tone: "medium" },
                    { label: "Avg Departure Delay", value: formatMinutes(kpis.avg_departure_delay_min), tone: "medium" },
                    { label: "Turnaround Score", value: formatPercent(kpis.avg_turnaround_score) },
                    { label: "Gate Assignment", value: formatPercent(kpis.gate_assignment_pct) },
                    { label: "Open Conflicts", value: formatNumber(kpis.open_conflicts, 0), tone: "high" },
                    { label: "High Risk Flights", value: formatNumber(kpis.high_risk_flights, 0), tone: "high" },
                ]}
            />

            <DataTable
                title="Live Flight Board"
                subtitle="Current flight board from the backend notebook payload."
                rows={data?.live_flight_board || []}
                maxRows={14}
                columns={[
                    { key: "flight_id", label: "Flight" },
                    { key: "airline", label: "Airline" },
                    { key: "origin", label: "Route", render: (_, row) => routeLabel(row) },
                    { key: "status", label: "Status", render: (value) => <StatusTag value={value} /> },
                    { key: "assigned_gate", label: "Gate" },
                    { key: "runway", label: "Runway" },
                    { key: "actual_departure_time", label: "Departure" },
                    { key: "turnaround_score", label: "Turnaround", render: (value) => formatPercent(value) },
                    { key: "delay_risk_level", label: "Risk", render: (value) => <StatusTag value={value} /> },
                ]}
            />

            <div className="module-grid module-grid-two">
                <DetailList
                    title="Open Conflicts"
                    subtitle="Conflicts generated by the flight-operations notebook."
                    items={data?.conflicts || []}
                    getTitle={(item) => `${item.flight_id} · ${item.type}`}
                    getBody={(item) => item.message}
                    getMeta={(item) => item.asset}
                    getTag={(item) => item.severity}
                    maxItems={8}
                />

                <DetailList
                    title="Top Risk Flights"
                    subtitle="Highest-risk movements with their current backend classification."
                    items={data?.top_risks || []}
                    getTitle={(item) => `${item.flight_id} · ${item.airline}`}
                    getBody={(item) => `${routeLabel(item)} · Gate ${item.assigned_gate} · ${formatMinutes(item.predicted_delay_min || item.arrival_delay_min || 0)}`}
                    getMeta={(item) => `${item.runway} · Bay ${item.parking_bay}`}
                    getTag={(item) => item.delay_risk_level || item.risk_level}
                    maxItems={8}
                />
            </div>

            <DataTable
                title="Priority Actions"
                subtitle="Backend recovery recommendations ranked by urgency."
                rows={data?.actions || []}
                maxRows={12}
                columns={[
                    { key: "priority_rank", label: "Priority" },
                    { key: "flight_id", label: "Flight" },
                    { key: "gate", label: "Gate" },
                    { key: "runway", label: "Runway" },
                    { key: "risk_level", label: "Risk", render: (value) => <StatusTag value={value} /> },
                    { key: "recommendation", label: "Recommendation" },
                ]}
            />
        </ModulePage>
    );
}
